export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"


export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"


export const USER_FACULTY_REQUEST = "USER_FACULTY_REQUEST"
export const USER_FACULTY_SUCCESS = "USER_FACULTY_SUCCESS"
export const USER_FACULTY_FAIL = "USER_FACULTY_FAIL"


export const USER_FACULTY_DETAIL_REQUEST = "USER_FACULTY_DETAIL_REQUEST"
export const USER_FACULTY_DETAIL_SUCCESS = "USER_FACULTY_DETAIL_SUCCESS"
export const USER_FACULTY_DETAIL_FAIL = "USER_FACULTY_DETAIL_FAIL"